<?php

namespace app\index\controller;

use app\common\controller\Frontend;

class Book extends Frontend
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    protected $noNeedLogin = '*';
    protected $noNeedRight = '*';
    protected $layout = '';

    //    图书搜索页
    public function book_list()
    {

        return $this->view->fetch();
    }

//    搜索页
    public function book_gj_seach()
    {

        return $this->view->fetch();
    }



//    图书详情页
    public function book_info()
    {

        return $this->view->fetch();
    }

//    特价图书

    public function special_book_list()
    {

        return $this->view->fetch();
    }


    //  推荐图书

    public function tj_book_list()
    {

        return $this->view->fetch();
    }


//    畅享书排行

    public function  book_rank_list(){


        return $this->view->fetch();
    }


}
